### ISSUE TITLE
Executive-Create Speech -Add clear instruction to login to the Microsoft 365

### ISSUE THREAD

**Issue by PayalGuruprasad** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#1]
# Module: # Create a speech using Copilot in Word
#### Step: 04.

Description of issue: 
Need to share the Microsoft 365 URL

**The current instruction :**
In Microsoft 365, open Microsoft Word, and then open a new blank document.

**Modification suggested:**

1. Open tab in your Edge browser, by entering the following URL: https://www.office.com
2. Login to the Microsoft 365 tab with the labuser creds 
3. In Microsoft 365, open Microsoft Word, and then open a new blank document.

**Comment by maquinl** [comment]
updated step 4  to be:

"In **Microsoft 365**, open a new blank **Microsoft Word** document by entering the following URL: **Word.new** "
