### ISSUE TITLE
"Create a speech using Copilot in Word" Lab: Missing "Reference Your Content" feature

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#15]
Issue: the "Reference your content" button is missing in the current version of Word. This prevents the lab from being completed as designed. It might've been a recent change to Word that should be synced into the instruction flow.

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/1765732/a91f30e5-f18c-47a0-90de-6cffb4591861)

**Comment by maquinl** [comment]
Hi @VitalyMCT.

In the image above you have the Copilot "chat" experience opened. 

When you first launch word.new, the copilot icon on the left of the screen is the option you want to select ( "Draft with copilot"):

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/37308730/57e06c24-192a-449e-b8dd-7109e3496a74)

in the draft with copilot functionality  you can "reference your content"

**Comment by VitalyMCT** [comment]
Thanks @maquinl .

Can we perhaps insert an extra step between current steps 4 and 5 to direct the user to open the Draft with Copilot window? 

They need to click Alt-I to explicitly open that "Draft with Copilot" window, it does not open automatically as soon as they open the Word document. I think many folks would then be inclined to click Copilot and get to the chat experience (same as I originally did).

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/1765732/a0cd3de1-0467-4264-87d0-0e90909b662e)

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/1765732/4bc799e3-7949-429f-af76-944277a99389)
