### ISSUE TITLE
Bing Enterprise - Cannot Export to Word

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#18]
The UI / featureset probably changed in this area, which impacts the ability to complete this lab. The Export feature appears to have been removed (or perhaps moved somewhere else).

Instructions: https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/blob/master/Instructions/Labs/M03-empower-workforce-copilot-it/2-create-project-plan.md

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/1765732/d90d1ea1-a2db-4b45-b1f3-66958f19ad66)

The intended UI appears to be per https://it.cornell.edu/microsoft-copilot-enterprise/save-copilot-responses

**Comment by maquinl** [comment]
@VitalyMCT There seems to be something going on with different Copilot experiences. I tested this and got both results, the option to export and then tried again and the option was removed. 

I'll need to investigate this further. In the meantime, i have added the following note as a workaround:

" > **NOTE:** If the export option is not available, copy the output into a new Word document (navigate to word.new in your browser) and save it as "Contoso CipherGuard project plan.docx". Then, skip step 15."
