### ISSUE TITLE
Create a slide presentation using Copilot in PowerPoint: Unable to view the embedded Screenshot in the instructions.

### ISSUE THREAD

**Issue by PayalGuruprasad** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#2]
# Module: 1
#### Step: 4 and 11

Description of issue:
Unable to view the embedded Screenshot in the instructions.
Repro steps:

1. In the instructions, the embedded screenshot is not seen :
![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/166609408/af80135b-ec54-4ec1-8c4b-c403476e1075)

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/166609408/12001fdc-5dd6-4048-bb13-1e8fff655692)
<img width="851" alt="unable to view the screenshot" src="https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/166609408/40762dbe-e5cd-4c7a-8593-8b99b3aca799">

**Comment by maquinl** [comment]
Resolved image issue accross course
#6 #10 #11 #12 #14
