### ISSUE TITLE
Descoped lab segments in Authorized Lab Host environments

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#20]
The Skillable lab environment is missing labs across various paths in this course. We have ticket 2299043 open there around this.

Although this was initially suspected to be a bug, it was explained as "by design":

> In GitHub we have all exercises from MS-4004 training material ported to GitHub. However, in the lab profile we intentionally removed the labs that required an email thread or pre-existing meeting (for Recap functionality). This is because in the current tenant environment we have not found a solution to enable that functionality yet. 

Although this solves one issue it creates many others: 

* Attendees are told they will be doing things that are missing from the scoped-down paths. For example, the 1st path is for Executives. Two out of 4 activities listed on page 1 are missing:

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/1765732/2f2deb15-19a5-4306-91c8-1a83dac190e4)

* Missing Teams and Outlook activities diminish the usefulness of the labs. Many attendees want to see Teams activities especially and expect them to be present in the labs (especially, but not exclusively due to expectations set above that they will be present).

* Blank pages for missing activities. This is less of an issue compared to the above, however, it's still confusing to the attendees. They are led to think that something is broken:

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/1765732/7df92694-b1f7-4164-964e-c551acc039bd)

* Significantly different sizes between the lab paths make them difficult to manage during delivery. For example, the scoped-down Executive path is left with 2 labs, whereas the Operations path has 4 labs.

* It's impossible for MCTs to tell from GitHub which scope is present and which scope is removed. This makes it harder for us to prepare. Usually in MicrosoftLearning GitHub projects everything feeds 1-1 into ALH environments.

Can this partial removal situation please be thoroughly reviewed & adjusted to be done in a more comprehensive manner?

**Comment by VitalyMCT** [comment]
Hi @maquinl.

I believe from the issue log that you are helping resolve many issues in this repo :)

Can you please review this one?

**Comment by maquinl** [comment]
@VitalyMCT This is indeed "By design" as they are a 1 to 1 copy of the Learning paths (ref: https://learn.microsoft.com/en-us/training/paths/empower-workforce-copilot-use-cases/).  This approach differs from other ILT (Instructor-Led Training) deliveries where we typically include labs designed to complement the learning material. In this case, there are multiple modalities available for the course, so labs are not included. For sessions utilizing the Skillable Tenant + Lab environment where these exercises are referenced, we've removed certain instructions due to limitations within the tenant environment itself. At this time, there are no plans to change this approach.

**Comment by VitalyMCT** [comment]
@maquinl Respectfully, MCTs cannot communicate to attendees that these instructional design issues are "by design" and retain any credibility.

For example, please consider the first bullet point mentioned in this issue report:
 
Attendees are told they will be doing 4 activities. Suddenly ... they are only given 2. 50% of the work is MIA for reasons unknown. It makes no sense whatsoever from their perspective as customers to have such major breakdown in expectations set vs reality presented.

I understand the motivation of attempting to support different delivery modalities via the same GitHub repo. I appreciate it makes sense as a cost-saving measure. However, it also needs to be considered from a customer satisfaction perspective.

The issues outlined here are real and they have been noted across multiple real-world deliveries. Please reconsider addressing them.
