### ISSUE TITLE
All download file links are broken with no public access

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#22]
All file links throughout the lab you're instructed to access and download are showing no access.

Example: 

[Fabrikam's 2023 Income Statement](https://edxinteractivepage.blob.core.windows.net/ms-4004/Fabrikam%202023%20Income%20Statement.docx).

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/94069201/c4b8d98c-1d45-4c72-8f67-69408132d6ee)

**Comment by maquinl** [comment]
@SkillableBB this has now been resolved. Please test and confirm. If the issue still occurs, reopen this issue. Thanks!
