### ISSUE TITLE
Issue referencing file from OneDrive

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#23]
A few attendees in my workshop this week are experiencing error messages while trying to reference files in OneDrive from Copilot prompts.

The errors vary from one Copilot experience to another. Here's one example:

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/1765732/36ee9813-55d7-4096-a2f6-f1f2838c4e33)

We've already verified a number of things, including:

1. Files are synced up to OneDrive and show up there via the browser
2. Link is correctly copied from OneDrive to the "/" interface
3. The prompt is correct
4. Same user is logged in to both Copilot and OneDrive
5. Document is in supported format (it's one of the Word documents in the labs)
6. Waited a bit after the upload and reopened the Copilot window. This seems to have helped in some cases, but not all.

Any ideas what's causing the issue and how to resolve it?

**Comment by VitalyMCT** [comment]
To add, there are additional details at https://techcommunity.microsoft.com/t5/copilot-for-microsoft-365/the-quot-reference-a-file-quot-feature-not-working-as-documented/m-p/3998347. 

It seems that one potential cause of this issue is latency in Semantic Index picking up the file and making it available to Copilot.

In case it matters, we are running the session in Skillable's ALH environment, with the built-in M365 tenants.

**Comment by VitalyMCT** [comment]
Hi @maquinl. 

I believe from the issue log that you are helping resolve many issues in this repo :)

Can you please review this one?

**Comment by VitalyMCT** [comment]
Additional insights from recent sessions below. This is definitely a significant issue in terms of attendee experience. Needs a consistently working solution ASAP please.

1. MRU-based access does not pick up the files referenced before
1. File browse screen does not see OneDrive files
2. URL/Link based access produces various errors, including this one:

![image](https://github.com/user-attachments/assets/a192f58e-bc85-45a9-8c1c-fc8cdbcaa6ac)

The only method that seems to work consistently is referencing the file by name only:

![image](https://github.com/user-attachments/assets/97481580-81dd-4035-b4f2-0a2f24dca05b)

This is all within the Skillable ALH.

**Comment by maquinl** [comment]
@VitalyMCT Yes, I am seeing the same behavior with the specific tenant + Lab profile combo being used (@LODSPRODMC..). I have been unable to find a workaround. I will continue to investigate this and will let you know should a solution be found.

**Comment by VitalyMCT** [comment]
@maquinl Can you please provide an update? Is this issue being actively worked on? If not, or if a solution still cannot be found after 4 months, can the labs be updated so they do not ask attendees to do something the system cannot do?

**Comment by maquinl** [comment]
Hi @VitalyMCT - Yesterday, we implemented a script to download all resource files directly to the local C drive of the desktop. We’ve now included instructions for users to upload these files to OneDrive at the start of each lab.

Example here: [MS-4004 Instructions](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/blob/master/Instructions/Labs/M01-empower-workforce-copilot-executives/1-introduction.md).

In our testing, this approach works well for most use cases, allowing OneDrive enough time to sync fully. However, for instances where syncing still doesn’t complete, we’ve added notes to guide users on copying the shared link from OneDrive and pasting it into the prompt as a workaround.

You should see this in MS-4005 as well.

**Comment by VitalyMCT** [comment]
@maquinl That's good news. 

Has this approach been propagated to the DW-101 as well, or does that MS-4004-based course remain to be updated with these fixes/workarounds? 

Also, regarding:

> However, for instances where syncing still doesn’t complete, we’ve added notes to guide users on copying the shared link from OneDrive and pasting it into the prompt as a workaround.

Have you observed this now working every time as a reliable workaround? Asking because it did not as of this Summer.

**Comment by maquinl** [comment]
HI @VitalyMCT - I'm not sure what 'DW-101' is. If it uses the VM provided by Skillable with Copilot access, then it should have the script, and the updated instructions should already be in place.

As for your second question, yes—several lab testers have confirmed that pasting in the copied shared link works as expected when the file can't be directly referenced from OneDrive.

**Comment by VitalyMCT** [comment]
@maquinl DW-101 is a Microsoft ESI course. It's derived heavily (in full?) from MS-4004 in this repo. To the best of my knowledge it's delivered exclusively on Skillable's ALH. 

DW-101 does not have a separate public repo. Microsoft and Skillable's team took this MS-4004 repo and made it into DW-101. 

As part of this some Copilot use cases, such as those involving M365 apps that are challenging to run in ALH setting (ex. Teams), were scoped out. I will do some pre-delivery validation in the coming days to ensure this issue is fully resolved in DW-101 as well.

Thanks for confirming the 2nd question.
