### ISSUE TITLE
Create a market research report using Copilot in Loop: Instruction to create new workspace should be clearer

### ISSUE THREAD

**Issue by PayalGuruprasad** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#3]
# Module: Empower-workforce -copilot-sales
#### Step: 2

Description of issue
In Microsoft Loop, the Workspaces tab is displayed by default. You want to create a new workspace for this project, so select the +New workspace button.

Suggested:
In Microsoft Loop, the Workspaces tab is displayed by default. You want to create a new workspace for this project, so select the +New workspace button. under the Get Started drop down

![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/166609408/23de0267-1609-4d48-bedb-62bd587538bb)

**Comment by maquinl** [comment]
changed instructions too "In **Microsoft Loop**, the **Workspaces** tab is displayed by default. You want to create a new workspace for this project, select **+** next to **Getting started**, and then select **+New workspace** button."
