### ISSUE TITLE
Compare supplier agreements using Copilot in Word :Downloading the files multiple times

### ISSUE THREAD

**Issue by PayalGuruprasad** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#4]
# Module: Empower-workforce-copilot-sales
#### Step: 01

Description of issue
Downloading the files multiple times.

Suggestion:
We can create a common drive in git and that drive location can be added to the instructions. So that leaners can download all the files at once and move them to the one drive location.

Current instructions needs multiple file download: suggested to create a common GIT file repository containing all the files.

Current instruction:
Select the following links to download the three supplier agreements:

[Contoso Supplier Agreement](https://edxinteractivepage.blob.core.windows.net/ms-4004/Contoso%20Supplier%20Agreement.docx)
[Tailwind Traders Supplier Agreement](https://edxinteractivepage.blob.core.windows.net/ms-4004/Tailwind%20Traders%20Supplier%20Agreement.docx)
[Wide World Importers Supplier Agreement](https://edxinteractivepage.blob.core.windows.net/ms-4004/Wide%20World%20Importers%20Supplier%20Agreement.docx)

**Comment by maquinl** [comment]
We have these files stored in Teams channel in the M365 tenant, we are working on a solution to allow students accounts to get access to the teams sites and then use those locations to reference for files. Once that's been implemented, i will update instructions accordingly to include teams file locations.
