### ISSUE TITLE
Remove the Azure Portal Link and Azure Subscription

### ISSUE THREAD

**Issue by Alfonsorodc** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#5]
Resources TAB

Description of issue
We don't need the Azure Portal Link, and the Subscription. That is confusing.

Repro steps:

1.Remove the Azure Portal Link and add the Microsoft 365 Link.

**Comment by maquinl** [comment]
I cant find where this is referenced - please link to the instructions you are referring too and re-open this issue, thanks!
