### ISSUE TITLE
Finance: Outlook Extra Info

### ISSUE THREAD

**Issue by Alfonsorodc** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#7]
# Module: Finance
#### Step: 13 and 14

Description of issue
It is not clear what text to introduce. This text seems not to make a lot of sense. We need also to review ther next steps

Repro steps:
![image](https://github.com/MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases/assets/32040167/33e62197-5b5d-4efc-a125-08d76f1f445e)

**Comment by maquinl** [comment]
This was caused by a bad indentation messing up the instruction order. I have resolved.
