### ISSUE TITLE
Create a project plan using Microsoft Copilot: The links should be provided in the instructions, and we should have clickable links in the instructions.

### ISSUE THREAD

**Issue by PayalGuruprasad** [MicrosoftLearning/MS-4004-Empower-workforce-copilot-use-cases#9]
# Module: Empower-workforce-copilot-IT
#### Step: 15

Description of issue: 
The links for the Microsoft 365 should be provided and should be ideally provided as highlighted T for easy access for the learners.

Repro steps:

15. The instruction: "In the Microsoft 365 tab in your browser, select Word. "

Suggested modification:

In the Microsoft 365 **### [T]https://www.office.com**  tab in your browser, select Word.

**Comment by maquinl** [comment]
reference #4
